### ISSUE TITLE
Ten phrases for scores in the end screen

### ISSUE THREAD

**Issue by hancandy** [Putaitu/HangoVR#19]
0-10%		- SUCH A SMOOTH CRIMINAL.  
11-20%		- They probably won't notice.  
21-30%		- They DO not look happy.  
31-40%		- You are not setting a foot outside of your room for a month.  
41-50%		- Your parents are selling your stuff for compensating the damage.  
51-60%		-  The restraining order against you is on your way.  
61-70%		- Someone is going to get kicked out of the house, go find a new flat.  
71-80%		- Better call your lawyer.  
81-90%		- You just won a free ticket to jail.  
91-100%		- HOLY SHIT THEY'RE GOING TO KILL YOU ALL.

**Comment by Rugerfred** [comment]
0-10%		- YOU'RE THE TRUE MASTER OF ORDER.
11-20%		- They probably won't notice.
21-30%		- They are not that happy.
31-40%		- Someone is going to get grounded for a month.
41-50%		- Forget your winter holydays for the next two years.
51-60%		- Someone is going to get kicked out of the house.
61-70%		- Better call your lawyer.
71-80%		- The restraining order against you is on your way.
81-90%		- You just won a free ticket to jail.
91-100%		- HOLY SHIT THEY'RE GOING TO KILL YOU ALL.

**Comment by hancandy** [comment]
0-10% - Such a smooth criminal
11-20% - They probably won't notice.
21-30% - Let's say they do NOT look happy
31-40% - You are not setting a foot outside of your room for a month
41-50% - Your parents are thinking about disowning you
51-60% - Someone is going to get kicked out of the house, go find a new flat.
61-70% - Better call your lawyer.
71-80% - The restraining order against you is on your way.
81-90% - You just won a free ticket to jail.
91-100% - HOLY SHIT THEY'RE GOING TO KILL YOU ALL.
